-- Comprehensive Memory Journal Prompts (600+ unique prompts)
-- Designed to help users remember and reflect on important life moments

-- Clear existing prompts first
DELETE FROM prompts;

-- Reset the sequence
ALTER SEQUENCE prompts_id_seq RESTART WITH 1;

-- Insert 600+ memory-focused prompts organized by categories
INSERT INTO prompts (text, category) VALUES

-- Childhood Memories (50 prompts)
('What is your earliest childhood memory?', 'childhood'),
('Describe your childhood bedroom in detail.', 'childhood'),
('What was your favorite toy as a child and why?', 'childhood'),
('Tell me about a childhood friend you remember fondly.', 'childhood'),
('What games did you love to play as a child?', 'childhood'),
('Describe a typical day during your childhood summers.', 'childhood'),
('What was your favorite subject in elementary school?', 'childhood'),
('Tell me about a teacher who made a lasting impression on you.', 'childhood'),
('What was your favorite book or story as a child?', 'childhood'),
('Describe a childhood birthday party you remember.', 'childhood'),
('What chores did you have to do as a child?', 'childhood'),
('Tell me about your childhood pet, if you had one.', 'childhood'),
('What was your favorite place to play as a child?', 'childhood'),
('Describe a family vacation from your childhood.', 'childhood'),
('What did you want to be when you grew up?', 'childhood'),
('Tell me about a time you got in trouble as a child.', 'childhood'),
('What was your favorite meal your mother or father made?', 'childhood'),
('Describe the neighborhood where you grew up.', 'childhood'),
('What traditions did your family have when you were young?', 'childhood'),
('Tell me about learning to ride a bike or swim.', 'childhood'),
('What was your favorite cartoon or TV show as a child?', 'childhood'),
('Describe a childhood fear you had.', 'childhood'),
('What was the best gift you ever received as a child?', 'childhood'),
('Tell me about a childhood adventure or exploration.', 'childhood'),
('What songs did you love to sing as a child?', 'childhood'),
('Describe your first day of school.', 'childhood'),
('What was your favorite season as a child and why?', 'childhood'),
('Tell me about a childhood injury or illness you remember.', 'childhood'),
('What was your favorite candy or treat as a child?', 'childhood'),
('Describe a time you felt really proud as a child.', 'childhood'),
('What was your favorite holiday as a child?', 'childhood'),
('Tell me about a childhood camping or outdoor experience.', 'childhood'),
('What was your favorite game to play with siblings or friends?', 'childhood'),
('Describe your childhood home in detail.', 'childhood'),
('What was your favorite thing to do on rainy days as a child?', 'childhood'),
('Tell me about learning something new as a child.', 'childhood'),
('What was your favorite piece of clothing as a child?', 'childhood'),
('Describe a childhood performance or recital you were in.', 'childhood'),
('What was your favorite snack after school?', 'childhood'),
('Tell me about a childhood collection you had.', 'childhood'),
('What was your favorite playground equipment?', 'childhood'),
('Describe a childhood sleepover or slumber party.', 'childhood'),
('What was your favorite thing about your childhood home?', 'childhood'),
('Tell me about a childhood hero or role model.', 'childhood'),
('What was your favorite way to spend allowance money?', 'childhood'),
('Describe a childhood talent show or competition.', 'childhood'),
('What was your favorite thing to do with your grandparents?', 'childhood'),
('Tell me about a childhood mystery or puzzle you tried to solve.', 'childhood'),
('What was your favorite childhood hiding spot?', 'childhood'),
('Describe the most exciting thing that happened in your childhood.', 'childhood'),

-- Family Relationships (60 prompts)
('Tell me about your parents and what they were like.', 'family'),
('Describe your relationship with your siblings.', 'family'),
('What is your favorite memory with your mother?', 'family'),
('What is your favorite memory with your father?', 'family'),
('Tell me about your grandparents and their influence on you.', 'family'),
('Describe a family tradition that was important to you.', 'family'),
('What family recipe do you remember and love?', 'family'),
('Tell me about a family reunion or gathering you enjoyed.', 'family'),
('What advice did your parents give you that you still remember?', 'family'),
('Describe your wedding day and how you felt.', 'family'),
('Tell me about the day your first child was born.', 'family'),
('What is your favorite memory with your spouse or partner?', 'family'),
('Describe a family vacation that was special to you.', 'family'),
('Tell me about a family member who inspired you.', 'family'),
('What family stories were passed down to you?', 'family'),
('Describe your role in your family growing up.', 'family'),
('Tell me about a time your family came together during a difficult time.', 'family'),
('What family holiday traditions do you cherish?', 'family'),
('Describe your children when they were young.', 'family'),
('Tell me about a family pet that was special to everyone.', 'family'),
('What is the funniest thing that ever happened at a family gathering?', 'family'),
('Describe your family home and what made it special.', 'family'),
('Tell me about a family member you wish you could see again.', 'family'),
('What family values were most important in your household?', 'family'),
('Describe a time you were really proud of a family member.', 'family'),
('Tell me about your family''s cultural background or heritage.', 'family'),
('What family photographs are most precious to you?', 'family'),
('Describe a family crisis and how you got through it together.', 'family'),
('Tell me about your relationship with your in-laws.', 'family'),
('What family nickname did you have and how did you get it?', 'family'),
('Describe a family celebration that was particularly meaningful.', 'family'),
('Tell me about a family member who had a great sense of humor.', 'family'),
('What family heirloom or keepsake is important to you?', 'family'),
('Describe your family''s Sunday or weekend routines.', 'family'),
('Tell me about a family member who was very talented.', 'family'),
('What family sayings or expressions do you remember?', 'family'),
('Describe a time you had to care for a family member.', 'family'),
('Tell me about your family''s approach to education.', 'family'),
('What family games or activities did you enjoy together?', 'family'),
('Describe a family member who was particularly wise.', 'family'),
('Tell me about your family''s religious or spiritual practices.', 'family'),
('What family meals or dinners do you remember most fondly?', 'family'),
('Describe a family member who overcame significant challenges.', 'family'),
('Tell me about your family''s attitude toward money and work.', 'family'),
('What family trips or outings were most memorable?', 'family'),
('Describe how your family celebrated birthdays.', 'family'),
('Tell me about a family member who was very generous.', 'family'),
('What family rules or expectations did you grow up with?', 'family'),
('Describe your family''s approach to handling disagreements.', 'family'),
('Tell me about a family member who was very creative.', 'family'),
('What family activities brought everyone together?', 'family'),
('Describe a family member who was particularly kind.', 'family'),
('Tell me about your family''s connection to your community.', 'family'),
('What family lessons about life do you carry with you?', 'family'),
('Describe how your family showed love and affection.', 'family'),
('Tell me about a family member who was very hardworking.', 'family'),
('What family memories make you smile the most?', 'family'),
('Describe your family''s approach to celebrating achievements.', 'family'),
('Tell me about a family member who was very adventurous.', 'family'),
('What family support meant the most to you in your life?', 'family'),

-- Career and Achievements (50 prompts)
('Tell me about your first job and what you learned.', 'career'),
('Describe your proudest professional achievement.', 'career'),
('What career path did you choose and why?', 'career'),
('Tell me about a mentor who influenced your career.', 'career'),
('Describe a challenging project you completed at work.', 'career'),
('What skills did you develop throughout your career?', 'career'),
('Tell me about a promotion or recognition you received.', 'career'),
('Describe your favorite job and what made it special.', 'career'),
('What was the most important lesson you learned at work?', 'career'),
('Tell me about a colleague who became a good friend.', 'career'),
('Describe a time you had to learn something completely new for work.', 'career'),
('What work accomplishment are you most proud of?', 'career'),
('Tell me about a difficult decision you had to make at work.', 'career'),
('Describe your retirement and how you felt about it.', 'career'),
('What advice would you give to someone starting in your field?', 'career'),
('Tell me about a time you helped train or mentor someone at work.', 'career'),
('Describe a work-related travel experience you enjoyed.', 'career'),
('What was your favorite aspect of your career?', 'career'),
('Tell me about a time you had to overcome a professional setback.', 'career'),
('Describe a work environment that you particularly enjoyed.', 'career'),
('What professional relationships were most meaningful to you?', 'career'),
('Tell me about a time you had to give an important presentation.', 'career'),
('Describe how your career evolved over the years.', 'career'),
('What work traditions or events did you look forward to?', 'career'),
('Tell me about a time you received helpful feedback at work.', 'career'),
('Describe a work project that you found particularly interesting.', 'career'),
('What professional goals did you set and achieve?', 'career'),
('Tell me about a time you had to work as part of a team.', 'career'),
('Describe your workspace and how you made it your own.', 'career'),
('What work-related skills are you most proud of developing?', 'career'),
('Tell me about a time you had to adapt to changes at work.', 'career'),
('Describe a work celebration or milestone you remember.', 'career'),
('What professional challenges helped you grow the most?', 'career'),
('Tell me about a time you had to solve a difficult problem at work.', 'career'),
('Describe your relationship with your supervisors over the years.', 'career'),
('What work-related volunteer activities did you participate in?', 'career'),
('Tell me about a time you had to meet a tight deadline.', 'career'),
('Describe how technology changed your work over the years.', 'career'),
('What professional development opportunities did you pursue?', 'career'),
('Tell me about a time you had to handle a difficult customer or client.', 'career'),
('Describe a work-related award or honor you received.', 'career'),
('What work habits served you well throughout your career?', 'career'),
('Tell me about a time you had to make a presentation to senior management.', 'career'),
('Describe your first day at a new job.', 'career'),
('What work-related friendships have lasted beyond your career?', 'career'),
('Tell me about a time you had to learn new technology for work.', 'career'),
('Describe a work-related conference or training you attended.', 'career'),
('What aspects of your work brought you the most satisfaction?', 'career'),
('Tell me about a time you had to handle multiple priorities at work.', 'career'),
('Describe how your career impacted your personal life and family.', 'career'),

-- Travel and Adventures (40 prompts)
('Describe your most memorable vacation or trip.', 'travel'),
('Tell me about a place you visited that took your breath away.', 'travel'),
('What was your favorite family vacation?', 'travel'),
('Describe a travel experience that didn''t go as planned.', 'travel'),
('Tell me about the farthest place you''ve ever traveled.', 'travel'),
('What was your favorite mode of transportation for travel?', 'travel'),
('Describe a local adventure or day trip you enjoyed.', 'travel'),
('Tell me about a travel companion who made the trip special.', 'travel'),
('What was the most beautiful natural sight you''ve ever seen?', 'travel'),
('Describe a cultural experience you had while traveling.', 'travel'),
('Tell me about your honeymoon or a romantic getaway.', 'travel'),
('What was your favorite hotel or place you stayed while traveling?', 'travel'),
('Describe a travel experience that taught you something new.', 'travel'),
('Tell me about a festival or event you attended while traveling.', 'travel'),
('What was the most adventurous thing you did while traveling?', 'travel'),
('Describe a travel experience with your children or grandchildren.', 'travel'),
('Tell me about a place you''d love to visit again.', 'travel'),
('What was your favorite meal you had while traveling?', 'travel'),
('Describe a travel experience that challenged you.', 'travel'),
('Tell me about a souvenir or memento from your travels.', 'travel'),
('What was your favorite road trip?', 'travel'),
('Describe a travel experience that was completely spontaneous.', 'travel'),
('Tell me about a place that felt like home even though it wasn''t.', 'travel'),
('What was your most relaxing vacation?', 'travel'),
('Describe a travel experience that was educational.', 'travel'),
('Tell me about a time you got lost while traveling.', 'travel'),
('What was your favorite beach or waterfront destination?', 'travel'),
('Describe a mountain or hiking experience you enjoyed.', 'travel'),
('Tell me about a city that you fell in love with.', 'travel'),
('What was your favorite camping or outdoor adventure?', 'travel'),
('Describe a travel experience that was physically challenging.', 'travel'),
('Tell me about a place where you felt completely at peace.', 'travel'),
('What was your favorite historical site or museum you visited?', 'travel'),
('Describe a travel experience that was emotionally moving.', 'travel'),
('Tell me about a place where you made unexpected friends.', 'travel'),
('What was your favorite seasonal destination (spring, summer, fall, winter)?', 'travel'),
('Describe a travel experience that exceeded your expectations.', 'travel'),
('Tell me about a place that was completely different from home.', 'travel'),
('What was your favorite travel photograph or memory?', 'travel'),
('Describe a travel experience that you''ll never forget.', 'travel'),

-- Friendships (40 prompts)
('Tell me about your best friend and how you met.', 'friendship'),
('Describe a friendship that has lasted many years.', 'friendship'),
('What is your favorite memory with a close friend?', 'friendship'),
('Tell me about a friend who helped you through a difficult time.', 'friendship'),
('Describe a fun adventure you had with friends.', 'friendship'),
('What qualities do you value most in a friend?', 'friendship'),
('Tell me about a friend who made you laugh until you cried.', 'friendship'),
('Describe a friendship that developed in an unexpected way.', 'friendship'),
('What is the kindest thing a friend has ever done for you?', 'friendship'),
('Tell me about a friend from your school days.', 'friendship'),
('Describe a friend who influenced your life in a positive way.', 'friendship'),
('What is your favorite tradition with a friend or group of friends?', 'friendship'),
('Tell me about a time you and a friend had a disagreement and worked it out.', 'friendship'),
('Describe a friend who shared your interests or hobbies.', 'friendship'),
('What is the most thoughtful gift you''ve received from a friend?', 'friendship'),
('Tell me about a friend who was very different from you but you got along well.', 'friendship'),
('Describe a friendship that began at work.', 'friendship'),
('What is your favorite way to spend time with friends?', 'friendship'),
('Tell me about a friend who was always there for you.', 'friendship'),
('Describe a group of friends you enjoyed spending time with.', 'friendship'),
('What is the funniest thing that happened with a friend?', 'friendship'),
('Tell me about a friend who taught you something important.', 'friendship'),
('Describe a friendship that rekindled after many years apart.', 'friendship'),
('What is your favorite memory of celebrating with friends?', 'friendship'),
('Tell me about a friend who was like family to you.', 'friendship'),
('Describe a friend who was very supportive of your dreams.', 'friendship'),
('What is the most memorable trip or outing you took with friends?', 'friendship'),
('Tell me about a friend who had a great sense of humor.', 'friendship'),
('Describe a friendship that formed through a shared challenge or experience.', 'friendship'),
('What is your favorite holiday or seasonal memory with friends?', 'friendship'),
('Tell me about a friend who was very generous with their time.', 'friendship'),
('Describe a friend who was always optimistic and uplifting.', 'friendship'),
('What is the most meaningful conversation you''ve had with a friend?', 'friendship'),
('Tell me about a friend who shared your values and beliefs.', 'friendship'),
('Describe a friendship that helped you grow as a person.', 'friendship'),
('What is your favorite memory of helping a friend?', 'friendship'),
('Tell me about a friend who was very creative or artistic.', 'friendship'),
('Describe a friend who was always up for an adventure.', 'friendship'),
('What is the most important lesson you learned from a friendship?', 'friendship'),
('Tell me about a friend who you wish you could reconnect with.', 'friendship'),

-- Life Lessons and Growth (50 prompts)
('What is the most important lesson life has taught you?', 'growth'),
('Tell me about a time you overcame a significant challenge.', 'growth'),
('Describe a moment when you realized you had grown as a person.', 'growth'),
('What mistake taught you the most valuable lesson?', 'growth'),
('Tell me about a time you had to be very brave.', 'growth'),
('Describe a decision that changed the course of your life.', 'growth'),
('What is the best advice you''ve ever received?', 'growth'),
('Tell me about a time you had to forgive someone.', 'growth'),
('Describe a moment when you felt truly proud of yourself.', 'growth'),
('What fear have you overcome in your life?', 'growth'),
('Tell me about a time you had to stand up for what you believed in.', 'growth'),
('Describe a situation where you learned the importance of patience.', 'growth'),
('What is the most difficult decision you''ve ever had to make?', 'growth'),
('Tell me about a time you learned from failure.', 'growth'),
('Describe a moment when you discovered something new about yourself.', 'growth'),
('What habit or behavior have you successfully changed?', 'growth'),
('Tell me about a time you had to ask for help.', 'growth'),
('Describe a situation where you learned the value of perseverance.', 'growth'),
('What is the most important thing you''ve learned about relationships?', 'growth'),
('Tell me about a time you had to adapt to a major change.', 'growth'),
('Describe a moment when you felt truly grateful.', 'growth'),
('What is the most valuable skill you''ve developed in life?', 'growth'),
('Tell me about a time you had to let go of something important.', 'growth'),
('Describe a situation where you learned about compassion.', 'growth'),
('What is the most important thing you''ve learned about yourself?', 'growth'),
('Tell me about a time you had to be very patient.', 'growth'),
('Describe a moment when you felt truly at peace.', 'growth'),
('What is the most challenging period you''ve lived through?', 'growth'),
('Tell me about a time you surprised yourself with your capabilities.', 'growth'),
('Describe a situation where you learned about empathy.', 'growth'),
('What is the most important thing you''ve learned about happiness?', 'growth'),
('Tell me about a time you had to be very disciplined.', 'growth'),
('Describe a moment when you felt truly confident.', 'growth'),
('What is the most valuable lesson you''ve learned about work?', 'growth'),
('Tell me about a time you had to be very understanding.', 'growth'),
('Describe a situation where you learned about resilience.', 'growth'),
('What is the most important thing you''ve learned about family?', 'growth'),
('Tell me about a time you had to be very honest about something difficult.', 'growth'),
('Describe a moment when you felt truly inspired.', 'growth'),
('What is the most valuable lesson you''ve learned about friendship?', 'growth'),
('Tell me about a time you had to be very generous.', 'growth'),
('Describe a situation where you learned about humility.', 'growth'),
('What is the most important thing you''ve learned about love?', 'growth'),
('Tell me about a time you had to be very courageous.', 'growth'),
('Describe a moment when you felt truly content.', 'growth'),
('What is the most valuable lesson you''ve learned about money?', 'growth'),
('Tell me about a time you had to be very flexible.', 'growth'),
('Describe a situation where you learned about wisdom.', 'growth'),
('What is the most important thing you''ve learned about aging?', 'growth'),
('Tell me about the most transformative experience of your life.', 'growth'),

-- Traditions and Holidays (40 prompts)
('Describe your favorite holiday tradition growing up.', 'traditions'),
('Tell me about how your family celebrated Christmas or your winter holiday.', 'traditions'),
('What is your favorite Thanksgiving or harvest celebration memory?', 'traditions'),
('Describe a birthday tradition that was special in your family.', 'traditions'),
('Tell me about how you celebrated New Year''s Eve.', 'traditions'),
('What is your favorite Easter or spring celebration memory?', 'traditions'),
('Describe a wedding tradition that you participated in or observed.', 'traditions'),
('Tell me about a cultural or ethnic tradition that was important to your family.', 'traditions'),
('What is your favorite memory of celebrating the Fourth of July or your national holiday?', 'traditions'),
('Describe a religious or spiritual tradition that was meaningful to you.', 'traditions'),
('Tell me about a family reunion tradition.', 'traditions'),
('What is your favorite Halloween or autumn celebration memory?', 'traditions'),
('Describe a graduation or achievement celebration tradition.', 'traditions'),
('Tell me about a holiday meal that was always special.', 'traditions'),
('What is your favorite memory of decorating for a holiday?', 'traditions'),
('Describe a tradition you started with your own family.', 'traditions'),
('Tell me about a community or neighborhood tradition you participated in.', 'traditions'),
('What is your favorite memory of giving or receiving gifts?', 'traditions'),
('Describe a tradition that involved music or singing.', 'traditions'),
('Tell me about a holiday or celebration that was unique to your region.', 'traditions'),
('What is your favorite memory of a holiday performance or pageant?', 'traditions'),
('Describe a tradition that involved cooking or baking together.', 'traditions'),
('Tell me about a tradition that brought extended family together.', 'traditions'),
('What is your favorite memory of a holiday party or gathering?', 'traditions'),
('Describe a tradition that involved giving back to the community.', 'traditions'),
('Tell me about a tradition that marked the changing of seasons.', 'traditions'),
('What is your favorite memory of a holiday craft or activity?', 'traditions'),
('Describe a tradition that involved storytelling.', 'traditions'),
('Tell me about a tradition that was passed down through generations.', 'traditions'),
('What is your favorite memory of a holiday game or activity?', 'traditions'),
('Describe a tradition that involved traveling or visiting special places.', 'traditions'),
('Tell me about a tradition that celebrated achievements or milestones.', 'traditions'),
('What is your favorite memory of a holiday surprise?', 'traditions'),
('Describe a tradition that involved creating something together.', 'traditions'),
('Tell me about a tradition that honored ancestors or family history.', 'traditions'),
('What is your favorite memory of a holiday that didn''t go as planned?', 'traditions'),
('Describe a tradition that involved helping others.', 'traditions'),
('Tell me about a tradition that celebrated friendship.', 'traditions'),
('What is your favorite memory of starting a new tradition?', 'traditions'),
('Describe a tradition that you hope will continue for future generations.', 'traditions'),

-- Love and Relationships (40 prompts)
('Tell me about how you met your spouse or life partner.', 'love'),
('Describe your first date with someone special.', 'love'),
('What is your favorite romantic memory?', 'love'),
('Tell me about a time you knew you were in love.', 'love'),
('Describe your wedding day or commitment ceremony.', 'love'),
('What is the most romantic gesture someone has made for you?', 'love'),
('Tell me about a relationship that taught you about love.', 'love'),
('Describe a time you had to work through a relationship challenge.', 'love'),
('What is your favorite memory of celebrating an anniversary?', 'love'),
('Tell me about a love letter or romantic note you received or wrote.', 'love'),
('Describe a relationship that grew stronger over time.', 'love'),
('What is the most important thing you''ve learned about love?', 'love'),
('Tell me about a time you felt deeply appreciated by someone you love.', 'love'),
('Describe a romantic trip or getaway you took.', 'love'),
('What is your favorite memory of Valentine''s Day or another romantic holiday?', 'love'),
('Tell me about a time you had to be vulnerable in a relationship.', 'love'),
('Describe a relationship tradition that was special to you.', 'love'),
('What is the most meaningful gift you''ve given or received in a relationship?', 'love'),
('Tell me about a time you and your partner supported each other through difficulty.', 'love'),
('Describe a moment when you felt completely understood by someone.', 'love'),
('What is your favorite memory of laughing together with someone you love?', 'love'),
('Tell me about a relationship that changed your perspective on life.', 'love'),
('Describe a time you had to forgive or be forgiven in a relationship.', 'love'),
('What is the most romantic place you''ve ever been?', 'love'),
('Tell me about a relationship that taught you about compromise.', 'love'),
('Describe a moment when you felt truly cherished.', 'love'),
('What is your favorite memory of a quiet, intimate moment with someone special?', 'love'),
('Tell me about a relationship that helped you grow as a person.', 'love'),
('Describe a time you had to be patient in a relationship.', 'love'),
('What is the most important quality you look for in a partner?', 'love'),
('Tell me about a relationship milestone that was meaningful to you.', 'love'),
('Describe a time you felt proud of your partner or loved one.', 'love'),
('What is your favorite memory of doing something thoughtful for someone you love?', 'love'),
('Tell me about a relationship that taught you about trust.', 'love'),
('Describe a moment when you felt completely accepted for who you are.', 'love'),
('What is the best relationship advice you''ve ever received or given?', 'love'),
('Tell me about a time you had to be brave in a relationship.', 'love'),
('Describe a relationship that brought out the best in you.', 'love'),
('What is your favorite memory of planning something special together?', 'love'),
('Tell me about what love means to you now compared to when you were younger.', 'love'),

-- Hobbies and Interests (40 prompts)
('Tell me about a hobby that has brought you great joy.', 'hobbies'),
('Describe a creative project you''re proud of completing.', 'hobbies'),
('What is your favorite way to spend free time?', 'hobbies'),
('Tell me about a skill you taught yourself.', 'hobbies'),
('Describe a collection you''ve enjoyed building over the years.', 'hobbies'),
('What is your favorite book and why did it impact you?', 'hobbies'),
('Tell me about a sport or physical activity you''ve enjoyed.', 'hobbies'),
('Describe a musical instrument you''ve played or wanted to learn.', 'hobbies'),
('What is your favorite type of music and why?', 'hobbies'),
('Tell me about a craft or artistic pursuit you''ve enjoyed.', 'hobbies'),
('Describe your favorite way to spend time in nature.', 'hobbies'),
('What is your favorite game (board game, card game, etc.) and who do you like to play with?', 'hobbies'),
('Tell me about a club or organization you''ve been part of.', 'hobbies'),
('Describe a hobby that connects you with other people.', 'hobbies'),
('What is your favorite type of movie or TV show?', 'hobbies'),
('Tell me about a puzzle or brain teaser you''ve enjoyed solving.', 'hobbies'),
('Describe your favorite way to be creative.', 'hobbies'),
('What is your favorite outdoor activity?', 'hobbies'),
('Tell me about a hobby that helps you relax.', 'hobbies'),
('Describe a skill you''ve developed that others admire.', 'hobbies'),
('What is your favorite way to learn new things?', 'hobbies'),
('Tell me about a hobby that has evolved over the years.', 'hobbies'),
('Describe your favorite place to pursue your hobbies.', 'hobbies'),
('What is your favorite type of food to cook or bake?', 'hobbies'),
('Tell me about a hobby that has taken you to interesting places.', 'hobbies'),
('Describe a project that took you a long time to complete.', 'hobbies'),
('What is your favorite way to express yourself creatively?', 'hobbies'),
('Tell me about a hobby that has connected you with your heritage or culture.', 'hobbies'),
('Describe your favorite way to stay physically active.', 'hobbies'),
('What is your favorite type of photography or subject to photograph?', 'hobbies'),
('Tell me about a hobby that has taught you patience.', 'hobbies'),
('Describe a skill that has been useful in many areas of your life.', 'hobbies'),
('What is your favorite way to spend time with your hands (crafting, building, etc.)?', 'hobbies'),
('Tell me about a hobby that has brought you recognition or awards.', 'hobbies'),
('Describe your favorite way to enjoy the arts (theater, museums, concerts, etc.).', 'hobbies'),
('What is your favorite type of writing or journaling?', 'hobbies'),
('Tell me about a hobby that has helped you through difficult times.', 'hobbies'),
('Describe a skill you''re still working to improve.', 'hobbies'),
('What is your favorite way to share your hobbies with others?', 'hobbies'),
('Tell me about a hobby that has surprised others who know you.', 'hobbies'),

-- Daily Life and Simple Pleasures (40 prompts)
('What is your favorite time of day and why?', 'daily_life'),
('Describe your perfect morning routine.', 'daily_life'),
('Tell me about a simple pleasure that always makes you smile.', 'daily_life'),
('What is your favorite room in your home and why?', 'daily_life'),
('Describe your favorite way to spend a quiet evening.', 'daily_life'),
('Tell me about a daily ritual that brings you comfort.', 'daily_life'),
('What is your favorite season and what do you love about it?', 'daily_life'),
('Describe your favorite way to start the weekend.', 'daily_life'),
('Tell me about a small act of kindness you witnessed or experienced.', 'daily_life'),
('What is your favorite comfort food and when do you enjoy it?', 'daily_life'),
('Describe your favorite way to spend time alone.', 'daily_life'),
('Tell me about a daily habit that has served you well.', 'daily_life'),
('What is your favorite type of weather and how do you enjoy it?', 'daily_life'),
('Describe your favorite way to connect with neighbors or community.', 'daily_life'),
('Tell me about a routine shopping trip or errand that you actually enjoy.', 'daily_life'),
('What is your favorite way to treat yourself?', 'daily_life'),
('Describe your favorite place to sit and think or relax.', 'daily_life'),
('Tell me about a daily interaction that brightens your day.', 'daily_life'),
('What is your favorite way to wake up in the morning?', 'daily_life'),
('Describe your favorite evening wind-down routine.', 'daily_life'),
('Tell me about a simple tradition you have with yourself.', 'daily_life'),
('What is your favorite way to enjoy your morning coffee, tea, or beverage?', 'daily_life'),
('Describe your favorite way to spend a rainy day.', 'daily_life'),
('Tell me about a daily moment when you feel most grateful.', 'daily_life'),
('What is your favorite way to organize or arrange your living space?', 'daily_life'),
('Describe your favorite way to spend time in your garden or with plants.', 'daily_life'),
('Tell me about a daily routine that helps you feel centered.', 'daily_life'),
('What is your favorite way to enjoy the changing seasons?', 'daily_life'),
('Describe your favorite way to prepare for sleep.', 'daily_life'),
('Tell me about a daily moment when you feel most peaceful.', 'daily_life'),
('What is your favorite way to enjoy a meal by yourself?', 'daily_life'),
('Describe your favorite way to spend the first hour after waking up.', 'daily_life'),
('Tell me about a daily practice that keeps you healthy.', 'daily_life'),
('What is your favorite way to enjoy natural light in your home?', 'daily_life'),
('Describe your favorite way to end the day.', 'daily_life'),
('Tell me about a daily moment when you feel most content.', 'daily_life'),
('What is your favorite way to enjoy silence or quiet moments?', 'daily_life'),
('Describe your favorite way to transition between different parts of your day.', 'daily_life'),
('Tell me about a daily routine that connects you with something larger than yourself.', 'daily_life'),
('What is your favorite way to make an ordinary day feel special?', 'daily_life'),

-- Special Moments and Milestones (30 prompts)
('Tell me about the happiest day of your life.', 'milestones'),
('Describe a moment when you felt truly accomplished.', 'milestones'),
('What is your favorite birthday memory?', 'milestones'),
('Tell me about a graduation or educational milestone you achieved.', 'milestones'),
('Describe a moment when you felt truly proud of someone else.', 'milestones'),
('What is your favorite memory of a celebration in your honor?', 'milestones'),
('Tell me about a time you achieved a long-term goal.', 'milestones'),
('Describe a moment when you felt truly recognized for your efforts.', 'milestones'),
('What is your favorite memory of a surprise party or celebration?', 'milestones'),
('Tell me about a milestone that marked a new chapter in your life.', 'milestones'),
('Describe a moment when you felt truly blessed or fortunate.', 'milestones'),
('What is your favorite memory of celebrating someone else''s achievement?', 'milestones'),
('Tell me about a time you overcame something you thought was impossible.', 'milestones'),
('Describe a moment when you felt truly appreciated.', 'milestones'),
('What is your favorite memory of a life-changing announcement or news?', 'milestones'),
('Tell me about a milestone that took years to achieve.', 'milestones'),
('Describe a moment when you felt truly at the right place at the right time.', 'milestones'),
('What is your favorite memory of a ceremony or formal recognition?', 'milestones'),
('Tell me about a time you celebrated overcoming a fear or challenge.', 'milestones'),
('Describe a moment when you felt truly grateful for your journey.', 'milestones'),
('What is your favorite memory of a personal breakthrough or realization?', 'milestones'),
('Tell me about a milestone that brought your family together.', 'milestones'),
('Describe a moment when you felt truly proud of how far you''ve come.', 'milestones'),
('What is your favorite memory of achieving something others said you couldn''t do?', 'milestones'),
('Tell me about a time you celebrated a small victory that meant a lot to you.', 'milestones'),
('Describe a moment when you felt truly successful in your own terms.', 'milestones'),
('What is your favorite memory of a milestone that surprised you?', 'milestones'),
('Tell me about a time you felt truly ready for the next phase of your life.', 'milestones'),
('Describe a moment when you felt truly proud of your perseverance.', 'milestones'),
('What milestone are you most grateful to have experienced in your lifetime?', 'milestones');

-- Update the random function to work with the new prompts
CREATE OR REPLACE FUNCTION get_random_prompt()
RETURNS TABLE(id integer, text text, category text) AS $$
BEGIN
    RETURN QUERY
    SELECT p.id, p.text, p.category
    FROM prompts p
    ORDER BY RANDOM()
    LIMIT 1;
END;
$$ LANGUAGE plpgsql;
